### ISSUE TITLE
A lot of errors are hidden ?!

### ISSUE THREAD

**Issue by momala454** [SanderRonde/phpstan-vscode#111]
I don't know why, but my "problems" tab is currently not showing anything
![image](https://github.com/user-attachments/assets/ef75bb54-7c68-4d98-ac29-0a386f8eb1bf)

But I can see on the output that a lot of them are actually there
```
[11/18/2024, 10:27:39 AM] [client] Starting extension with configuration: {
	"phpstan.singleFileMode": false,
	"phpstan.binPath": "vendor/bin/phpstan",
	"phpstan.binCommand": [],
	"phpstan.configFile": "phpstan.neon,phpstan.neon.dist,phpstan.dist.neon",
	"phpstan.paths": {},
	"phpstan.dockerContainerName": "",
	"phpstan.rootDir": "",
	"phpstan.options": [],
	"phpstan.enableStatusBar": true,
	"phpstan.memoryLimit": "1G",
	"phpstan.enabled": true,
	"phpstan.projectTimeout": 300000,
	"phpstan.timeout": 300000,
	"phpstan.suppressTimeoutMessage": false,
	"phpstan.showProgress": false,
	"phpstan.showTypeOnHover": true,
	"phpstan.enableLanguageServer": false,
	"phpstan.ignoreErrors": [
		"Xdebug: .*"
	],
	"phpstan.suppressWorkspaceMessage": false,
	"phpstan.pro": false,
	"phpstan.tmpDir": "",
	"phpstan.checkValidity": false
}
[11/18/2024, 10:27:39 AM] [client] Initializing done
[11/18/2024, 10:27:39 AM] [client] Showing one-time messages (if needed)
[11/18/2024, 10:27:39 AM] [server] Language server ready
[11/18/2024, 10:27:39 AM] [server] Language server started
[11/18/2024, 10:27:40 AM] [server] PHPStan version: PHPStan - PHP Static Analysis Tool 2.0.2

[11/18/2024, 10:27:44 AM] [file-watcher] Checking: Initial check
[11/18/2024, 10:27:44 AM] [check:1] Check started for project
[11/18/2024, 10:27:44 AM] [status-bar] notification:' {"opId":0,"type":"new","tooltip":"Checking project"}
[11/18/2024, 10:27:44 AM] [status-bar] Showing status bar
[11/18/2024, 10:27:44 AM] [check:1] Spawning PHPStan with the following configuration:  {"binStr":"/home/blah/helllo/helllo-api/vendor/bin/phpstan","args":["analyse","-c","/home/blah/helllo/helllo-api/phpstan.neon","--error-format=json","--no-interaction","--memory-limit=1G","-a","/home/blah/.vscode-server/extensions/sanderronde.phpstan-vscode-3.2.16/_config/4f09c5c6606a8ac1b953d798f98a5522/autoload.php","-c","/home/blah/.vscode-server/extensions/sanderronde.phpstan-vscode-3.2.16/_config/4f09c5c6606a8ac1b953d798f98a5522/config.neon"]}
[11/18/2024, 10:27:44 AM] [process-spawner] Spawning process 11759 with timeout 900000
[11/18/2024, 10:27:44 AM] [process-spawner] Spawning process 11759 with timeout 900000
[11/18/2024, 10:27:47 AM] [status-bar] notification:' {"progress":{"done":0,"total":1988,"percentage":0},"opId":0,"type":"progress","tooltip":"Checking project - 0/1988 (0%)"}
[11/18/2024, 10:27:47 AM] [status-bar] notification:' {"progress":{"done":1988,"total":1988,"percentage":100},"opId":0,"type":"progress","tooltip":"Checking project - 1988/1988 (100%)"}
[11/18/2024, 10:27:49 AM] [check:1] PHPStan process exited succesfully
[11/18/2024, 10:27:49 AM] [status-bar] notification:' {"opId":0,"result":"Success","type":"done"}
[11/18/2024, 10:27:49 AM] [status-bar] Hiding status bar, last operation result = Success
[11/18/2024, 10:27:49 AM] [check:1] Check completed for project, errors= {"fileSpecificErrors":{"file:///home/............."]},"notFileSpecificErrors":[]}
```

config
```
includes:
    - phpstan-baseline.neon #TODO disable
    - phar://phpstan.phar/conf/bleedingEdge.neon
    - vendor/phpstan/phpstan-strict-rules/rules.neon
    - vendor/jbboehr/phpstan-laravel-validation/extension.neon
    - vendor/cuyz/valinor/qa/PHPStan/valinor-phpstan-configuration.php
    - vendor/larastan/larastan/extension.neon
parameters:
    level: 10
    treatPhpDocTypesAsCertain: true
    editorUrl: 'vscode://file/%%file%%:%%line%%'
    editorUrlTitle: '%%relFile%%:%%line%%'
    paths:
        - www
        - app
        - config
        - database
        - routes
        - swagger
    bootstrapFiles:
        - www/includes/App.php
    reportUnmatchedIgnoredErrors: false
    checkImplicitMixed: true
    reportMaybesInMethodSignatures: true
    reportMaybesInPropertyPhpDocTypes: true
    strictRules:
        disallowedLooseComparison: true
        booleansInConditions: false
        uselessCast: true
        requireParentConstructorCall: true
        #disallowedConstructs: false
        disallowedEmpty: false
        overwriteVariablesWithLoop: true
        closureUsesThis: true
        matchingInheritedMethodNames: true
        numericOperandsInArithmeticOperators: true
        #strictCalls: true
        switchConditionsMatchingType: true
        noVariableVariables: true
        strictArrayFilter: true
    ignoreErrors:
        - '#Dynamic call to static method Symfony\\Component\\HttpFoundation\\Response::.*#'
        - '#Dynamic call to static method Illuminate\\Http\\Request::validate\(\).#'
```

It looks like it is not reporting any error at all. I don't know when it started doing this
