### ISSUE TITLE
Config File Paths are not respected

### ISSUE THREAD

**Issue by HighLiuk** [SanderRonde/phpstan-vscode#43]
This is my `phpstan.neon` file:

```yaml
parameters:
  level: 8
  paths:
    - src
    - tests
```

but the paths are not respected. For instance, I have a `examples` folder that is sibling to `src`, and this is not skipped.
But the most annoying part is when you open a file inside `vendor`, and everything is covered with squiggly lines. But vendor is not in the `paths`.
Is this intended?
