### ISSUE TITLE
Issue with phpstan-doctrine

### ISSUE THREAD

**Issue by michalblocinski** [SanderRonde/phpstan-vscode#59]
I have an issue using phpstan-doctrine and phpstan-vscode extension. This is my phpstan.neon:
```
includes:
    - vendor/phpstan/phpstan-doctrine/extension.neon
    - vendor/phpstan/phpstan-doctrine/rules.neon
parameters:
    level: 9
    paths:
        - src
        - tests
    checkMissingIterableValueType: false
    ignoreErrors:
        - '#Method .+::dispatch\(\) invoked with 2 parameters, 1 required\.#'
        - '#Method .+ return type has no value type specified in iterable type .+#'
        - '#Method .+ has parameter .+ with no value type specified in iterable type array\.#'
        - '#Property .+::\$id is never written, only read\.#'
    stubFiles:
        - app/stubs/Symfony.stub
        - app/stubs/Filter.stub
        - app/stubs/json.stub
    doctrine:
        objectManagerLoader: app/stubs/object-manager.php

```
And when I run it this way via cli:
`<path>/phpstan analyse <path>/Repository.php -c <path>/phpstan.neon`
it will return list of errors. But when I use it as extension it does not report errors. This is output log:
```
[check:35] Spawning PHPStan with the following configuration:  {"binCmd":"<path>/phpstan","args":["analyse","-c","<path>/phpstan.neon","--error-format=raw","--no-interaction","--memory-limit=1G","--no-progress","<path>/Repository.php","-a","/var/folders/54/7q9csvqd5_qfg91kt6j_jklc0000gn/T/tmp-1004-LXYhMyo2G3LR/autoload.php","-c","/var/folders/54/7q9csvqd5_qfg91kt6j_jklc0000gn/T/tmp-1004-LXYhMyo2G3LR/config.neon"]}
[check:34] Check completed for file:///<path>/Repository.php errors= {}
```

I would expect same response to be for command via cli as well via extension
Additional information is that if I remove this part from phpstan.neon configuration:
```
doctrine:
        objectManagerLoader: app/stubs/object-manager.php
```
Extension again show errors correctly
